Step_5: added brain-even games
alekseifeniuk/python-project-lvl1 pull request #4
Opened 2022-01-28 18:31 UTC by alekseifeniuk

Hi, good evening!

https://ru.hexlet.io/projects/49/members/11286?step=5

2022-01-29 09:29 UTC, svntmr requested changes
please, fix the lint action (it fails).   
also, your README is missing asciinema with the game showcase

2022-01-29 09:29 UTC, svntmr commented on brain_games/cli.py
> +def is_even():
> cli.py не предназначен для описания логики игр.    

consider moving this function into some file in a special folder for games backend/logic, e. g. `brain_games/games`

2022-01-29 09:29 UTC, svntmr commented on brain_games/cli.py
> +    global user_name
global variables is a bad practice, consider refactoring welcome_user to return `user_name`. `user_name` definition from line 6 should be removed

2022-01-29 09:29 UTC, svntmr commented on brain_games/cli.py
> +def greet_user():
this function also should be refactored as `user_name` won't be global. do smth to pass user name into this function

2022-01-29 09:29 UTC, svntmr commented on brain_games/cli.py
> +def greet_user():
I'd rename it to `congratulate_user`

2022-01-29 09:29 UTC, svntmr commented on brain_games/cli.py
> +        user_answer = prompt.string('You answer: ')
You**r**

2022-01-29 09:29 UTC, svntmr commented on brain_games/cli.py
> +            print(f'Let\'s try again, {user_name}!')
you can use double quotes instead of `\'`

2022-01-29 09:29 UTC, svntmr commented on pyproject.toml
don't forget to update the project version with each step, `poerty version minor`

2022-01-29 09:29 UTC, svntmr commented on pyproject.toml
https://python-poetry.org/docs/cli/#version

2022-02-01 07:38 UTC, svntmr requested changes
the structure of the project is much better now!

2022-02-01 07:38 UTC, svntmr commented on brain_games/games/brain_even_rules.py
> +    game_task = randint(1, 500)
just to add, it's not necessary to name variables inside the function in the way they're named in caller code (e. g. you can name it `random number` if you want)

2022-02-01 07:38 UTC, svntmr commented on brain_games/game_core.py
> +    print(f'Hello, {name}!')
you can use `welcome_user` from cli module there, just update it to return user name

2022-02-01 07:38 UTC, svntmr commented on brain_games/game_core.py
> +        print(f'Question: {game_task}')
I'd move all printing functions into cli module

2022-02-01 07:38 UTC, svntmr commented on brain_games/game_core.py
> +        user_answer = prompt.string('Your answer: ')
prompt stuff should be in cli module as well

2022-02-01 07:38 UTC, svntmr commented on brain_games/game_core.py
> +            print('Correct!')
I'd move all printing functions into cli module

2022-02-01 07:38 UTC, svntmr commented on brain_games/game_core.py
> +            print(f"Let's try again, {name}!")
I'd move all printing functions into cli module

2022-02-01 07:38 UTC, svntmr commented on brain_games/game_core.py
> +        print(f'Congratulations, {name}!')
I'd move all printing functions into cli module

2022-02-03 07:49 UTC, svntmr requested changes
looks better and better!

2022-02-03 07:49 UTC, svntmr commented on brain_games/cli.py
> +def print_rules(game):
I think it's better to pass rules to this function instead of game module

2022-02-03 07:49 UTC, svntmr commented on brain_games/cli.py
> +def question(game_task):
I'd rename it to `ask_question`

2022-02-03 07:49 UTC, svntmr commented on brain_games/cli.py
> +def answer():
I'd rename it to `ask_answer`

2022-02-03 07:49 UTC, svntmr commented on brain_games/game_core.py
> +from brain_games.cli import welcome_user, print_rules
you can do multiline imports, like
```python
from ... import (
    a,
    b,
    c
)
```

2022-02-03 07:49 UTC, svntmr commented on brain_games/games/brain_even_rules.py
> +def rules():
I'd rename it to `get_game_round`

2022-02-03 07:49 UTC, svntmr commented on brain_games/game_core.py
> +from brain_games.games import brain_even_rules
I'd rename `brain_even_rules` to `brain_even` as you're importing a game, not its rules

2022-02-03 07:49 UTC, svntmr commented on brain_games/cli.py
>  def welcome_user():
I'd rename it to `welcome_and_acknowledge_user` as it returns user name now

2022-02-04 15:23 UTC, alekseifeniuk commented on brain_games/game_core.py
> +from brain_games.games import brain_even_rules
Hmm, then script file and game file will have similar name. I rename to brain_even_game, alright?

2022-02-05 10:58 UTC, svntmr requested changes
imho, this is the last review of this PR - you're close to the finish of step 5 :^)

2022-02-05 10:58 UTC, svntmr commented on README.md
> +https://asciinema.org/a/RjCfq3HtaGA7mBVgeWHPgTpUY
I'd add a new section for games and list games under it. Also, asciinema should be used as a markdown link (see the suggestion)
```suggestion
## Games in the project

### Brain Even
[![asciicast](https://asciinema.org/a/RjCfq3HtaGA7mBVgeWHPgTpUY.svg)](https://asciinema.org/a/RjCfq3HtaGA7mBVgeWHPgTpUY)
```

2022-02-05 10:58 UTC, svntmr commented on brain_games/game_core.py
> +    print_rules(brain_even_game.game_rules)
this file should be able to work with any game, but now it uses `brain_even_game` rule even if another game will be loaded. 
```suggestion
    print_rules(game.game_rules)
```

2022-02-05 10:58 UTC, svntmr commented on brain_games/game_core.py
> +from brain_games.games import brain_even_game
this import is not needed

2022-02-05 10:58 UTC, svntmr commented on brain_games/game_core.py
> +    for i in range(3):
[optional] python has a special variable for smth not needed - `_`. In this particular case `i` is not needed, you can replace it with `_` if you want. It's not necessary, but I'm looking for `i` usages when I'm seeing the loop with it

2022-02-06 08:29 UTC, svntmr commented
Looks good, ready to be merged!

2022-02-06 08:30 UTC, svntmr approved these changes

2022-02-06 08:33 UTC, merged