Step_6: add brain-calc game and black
alekseifeniuk/python-project-lvl1 pull request #5
Opened 2022-02-06 09:31 UTC by alekseifeniuk

New step - new code!

https://ru.hexlet.io/projects/49/members/11286?step=6

2022-02-06 11:00 UTC, svntmr requested changes
better with every PR

2022-02-07 15:47 UTC, alekseifeniuk commented on brain_games/games/brain_calc_game.py
> +    list_operations = [
Just remove one variable.

2022-02-07 15:55 UTC, svntmr commented on brain_games/games/brain_calc_game.py
> +    list_operations = [
no, I meant to pull it out of function and put in under the `game_rule` variable

2022-02-08 08:24 UTC, svntmr commented on .github/workflows/lint.yml
> +          poetry config virtualenvs.create false
`pip install pre-commit` can be removed from Run pre-commit step as it'll be automatically installed into global site-packages (because you've turned off virtualenvs creation)

2022-02-08 08:27 UTC, svntmr commented on README.md
> +[![asciicast](https://asciinema.org/a/at1hQBf2BInKTPWDA3wlU4r0n.svg)](https://asciinema.org/a/at1hQBf2BInKTPWDA3wlU4r0n)
this link point to asciinema with brain-even game

2022-02-08 08:29 UTC, svntmr commented on brain_games/games/brain_calc_game.py
> +def addition(one, two) -> Tuple[str, str]:
please, additionally type the arguments as well
```suggestion
def addition(one: int, two: int) -> Tuple[str, str]:
```

2022-02-08 08:30 UTC, svntmr commented on brain_games/games/brain_calc_game.py
> +def addition(one, two) -> Tuple[str, str]:
also, don't forget to update the project version with poetry

2022-02-08 16:46 UTC, svntmr commented on brain_games/cli.py
>  def print_rules(rules):
type hint is missing here for rules argument

2022-02-08 16:55 UTC, svntmr approved these changes

2022-02-08 16:56 UTC, merged